export const AUDIT_ACTIONS = [
  'login_success',
  'login_failed',
  'logout',
  'password_changed',
  'create',
  'update',
  'delete',
  'submit',
  'approve',
  'reject',
  'verify',
  'merge',
  'export',
  'import_commit',
  'backup_created',
  'settings_updated',
];

export const AUDIT_MODULES = [
  'auth',
  'User',
  'Faculty',
  'Department',
  'Session',
  'Semester',
  'Level',
  'GradingRule',
  'Course',
  'Student',
  'Result',
  'UploadBatch',
  'Verification',
  'TranscriptRequest',
  'SystemSetting',
  'Backup',
];
